<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="ClientDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.client" Member="clients">
    <Type Name="client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Operator" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="intspeed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sumofoperator" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="numberphone" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>